### ISSUE TITLE
[Bug] - clothing shop, mask, ears , etc esx_skin

### ISSUE THREAD

**Issue by Luca8120** [esx-framework/esx_core#1491] opened 2024-11-20 16:54 UTC
**Describe the bug**
You can see that if you go to the next shop, the items from the last shop also get shown in the other menu. (sry bad english iam german)

**Debug Info (please complete the following information):**
 - OS: Windows Server 2022
 -  FiveM Artifact 11194
 - ESX Version: 1.11.3

**Additional context**
https://youtu.be/06e1wMkCT0k

**Comment by Mycroft-Studios** [comment] 2024-11-20 17:03
This is intended behaviour, there is no bug here.

**Comment by Luca8120** [comment] 2024-11-20 17:08
it also happens in the barbershop

**Comment by Luca8120** [comment] 2024-11-20 17:08
now you can also change the mask in the barber shop, after you opened the other menus before

**Comment by Luca8120** [comment] 2024-11-20 17:08
@Mycroft-Studios

**Comment by Luca8120** [comment] 2024-11-20 17:09
and earpice and so on

**Comment by Luca8120** [comment] 2024-11-20 17:09
![Screenshot 2024-11-20 180910](https://github.com/user-attachments/assets/6cac4725-eee8-4698-abc3-7e0284212999)

**Comment by Luca8120** [comment] 2024-11-20 17:11
an t-shirt. its clearly a bug. why would you want to allow players to change t-shirts in barber shop

**Comment by Kenshiin13** [comment] 2024-11-20 18:03
@Luca8120 I will investigate. Thank you.

**Comment by Kenshiin13** [comment] 2024-11-20 18:41
@Luca8120 Should be fixed with [this PR](https://github.com/esx-framework/esx_core/pull/1492). Thanks for the report :)

**Closed by Kenshiin13** 2024-11-20 18:41 UTC
Labels: bug
