### ISSUE TITLE
[Bug] - (es_extended / esx_policejob) - vehicle duplicates

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx_core#515] opened 2022-09-30 11:56 UTC
**Describe the bug**
This bug allows people to spawn few same vehicles with identical properties.

**To Reproduce**
1. Go to police vehicle spawn
2. Select custom vehicle (which will load a little longer than vanila)
3. Spawn that vehicle and quickly get back to vehicle spawn menu by pressing Enter simultaneously
4. Vehicle will appear as stored and you can spawn it again

**Expected behavior**
Clearly you should not be able to spawn 2 same vehicles.

**Video**
https://streamable.com/t1s6a7

**Debug Info (please complete the following information):**
 - OS: Windows 11
 -  FiveM Artifact: 5949
 - ESX Version: 1.8.5

**Comment by Benzo00** [comment] 2022-10-02 17:19
i will take a look :)

**Comment by iSentrie** [comment] 2022-10-02 19:19
i might missed [refactor(es_extended): Client Vehicles Now on Client again](https://github.com/esx-framework/esx-legacy/commit/7ba262b702caf6428ebdb29a3f6375eb4ed0c6e2) this somehow, should be fixed on it

**Comment by iSentrie** [comment] 2022-10-17 03:41
This is currently present again, once moved on to onesync spawning.

**Comment by AstroNext** [comment] 2022-10-31 18:44
> This is currently present again, once moved on to onesync spawning.

Wait for new esx_policejob update.

**Comment by Taavi-AU** [comment] 2022-11-19 06:04
This has been fixed in my PR (https://github.com/esx-framework/esx-legacy/pull/684)

**Comment by Gellipapa** [comment] 2022-11-27 04:12
Hi! @Taavi-AU Can you look at it? Because I still have more than one car to spawn with that license plate. So if I spawn it, it doesn't disappear from the menu so I can spawn it again. I tested with basic cars. 

I have 3 vehicles and after spawn open menu i can see 3 vehicles and i can spawn.
![image](https://user-images.githubusercontent.com/22717950/204118837-a8e0b480-3f28-46a6-a219-ed8d15611139.png)

**Comment by Gellipapa** [comment] 2022-11-27 15:42
Hi! @iSentrie. Please update your esx and retest. Thank you. I wait your feedback.

**Comment by iSentrie** [comment] 2022-11-28 09:02
> Hi! @iSentrie. Please update your esx and retest. Thank you. I wait your feedback.

With thumbs up I didn't mean that it's okay, I meant I will test and result is the same as was before, this "fix" was introduced earlier and had same outcome, vehicles cannot be spawned at all (at least for me).

**Comment by Gellipapa** [comment] 2022-11-28 09:48
@iSentrie Ohh i see. Do you use latest esx version?  @Taavi-AU Any info?

**Comment by Taavi-AU** [comment] 2022-11-28 09:49
I have no idea what you have done wrong, this works perfectly fine for me, I downloaded a fresh version aswell when I tested yesterday.

**Comment by Gellipapa** [comment] 2022-11-28 09:51
Yes, it worked for me too.

**Comment by Taavi-AU** [comment] 2022-11-28 09:52
@iSentrie Make sure to use the latest version of esx_policejob, if you do use the latest then it should work, worked for me and Gelli.

**Comment by iSentrie** [comment] 2022-11-28 10:49
I do use latest one (es_extended (manually updating this one), esx_policejob). Anything else can interfere here?

**Comment by iSentrie** [comment] 2022-11-28 14:46
This is with @Taavi-AU version, same with source version.
https://user-images.githubusercontent.com/29688478/204306570-25ee4375-5790-4879-8baa-8419d1989c3a.mp4

**Comment by Taavi-AU** [comment] 2022-11-28 14:47
It doesnt even show stored or not in garage on the menu

**Comment by iSentrie** [comment] 2022-11-28 14:48
> 

Yup and this video taken with default esx menu.

**Comment by Taavi-AU** [comment] 2022-11-28 14:49
Does your owned_vehicles table have a stored column?

**Comment by Taavi-AU** [comment] 2022-11-28 14:49
When a vehicle is stored it should update to 1, and if it is removed it should update to 0, which it does for me

**Comment by iSentrie** [comment] 2022-11-28 14:51
> Does your owned_vehicles table have a stored column?



> When a vehicle is stored it should update to 1, and if it is removed it should update to 0, which it does for me

![image](https://user-images.githubusercontent.com/29688478/204307767-f47f457b-d028-45d7-962c-59e2b18450d4.png)

**Comment by Taavi-AU** [comment] 2022-11-28 14:52
That's really strange, I honestly am unsure what could cause this. Are the vehicles you are spawning custom or gta vehicles

**Comment by iSentrie** [comment] 2022-11-28 14:53
> That's really strange, I honestly am unsure what could cause this. Are the vehicles you are spawning custom or gta vehicles

Tried both, vanila from default esx policejob and custom too.

And here of my old police job, which works just fine.
![image](https://user-images.githubusercontent.com/29688478/204308272-89c7d242-83ee-415e-ae9a-eac5e1b04382.png)

**Comment by Taavi-AU** [comment] 2022-11-28 14:54
Okay, I will do further testing with it, but it all worked for me so i am unsure what to say

**Comment by iSentrie** [comment] 2022-11-28 15:07
> Okay, I will do further testing with it, but it all worked for me so i am unsure what to say

i wonder how it all works for others

**Comment by Gellipapa** [comment] 2022-11-28 17:44
@iSentrie Remove cache folder and try retest, I think cached or you can't overwrite but interesting problem.

**Comment by AstroNext** [comment] 2022-11-28 20:23
> @iSentrie Remove cache folder and try retest, I think cached or you can't overwrite but interesting problem.

I fix this problem in my server only with this function ( tonumber(vehicleStatus) ) i think this fix this issue

**Comment by AstroNext** [comment] 2022-11-29 10:41
> > I fix this problem in my server only with this function ( tonumber(v.stored) ) i think this fix this issue
> 
> this would only return nil then
> 
> > @iSentrie Remove cache folder and try retest, I think cached or you can't overwrite but interesting problem.
> 
> `v.stored` returns `true` or `false` ![image](https://user-images.githubusercontent.com/29688478/204505756-77c8b2b7-e9c5-4495-b048-4da563015b96.png)
> 
> changing code to
> 
> ```lua
> if v.stored == true then
>     label = label .. ('<span style="color:green;">%s</span>'):format(TranslateCap('garage_stored'))
> elseif v.stored == false then
>     label = label .. ('<span style="color:darkred;">%s</span>'):format(TranslateCap('garage_notstored'))
> end
> ```
> 
> fixes this issue, which leads to conclusion that any of this PR (#684) was unnecessary and only breaking the code. we don't need to write additionally `if v.stored == true then` or `if v.stored == 1 then` because simply `if v.stored then` was more than enough.

in old version of ESX, sql Library is mysql-async, if you store true or false in sql that record 1 or 0 then if you query true or false data that return you string's of 1 or 0 . I think that fixed in oxmysql .

**Comment by iSentrie** [comment] 2022-11-29 10:43
> > > I fix this problem in my server only with this function ( tonumber(v.stored) ) i think this fix this issue
> > 
> > 
> > this would only return nil then
> > > @iSentrie Remove cache folder and try retest, I think cached or you can't overwrite but interesting problem.
> > 
> > 
> > `v.stored` returns `true` or `false` ![image](https://user-images.githubusercontent.com/29688478/204505756-77c8b2b7-e9c5-4495-b048-4da563015b96.png)
> > changing code to
> > ```lua
> > if v.stored == true then
> >     label = label .. ('<span style="color:green;">%s</span>'):format(TranslateCap('garage_stored'))
> > elseif v.stored == false then
> >     label = label .. ('<span style="color:darkred;">%s</span>'):format(TranslateCap('garage_notstored'))
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes this issue, which leads to conclusion that any of this PR (#684) was unnecessary and only breaking the code. we don't need to write additionally `if v.stored == true then` or `if v.stored == 1 then` because simply `if v.stored then` was more than enough.
> 
> in old version of ESX, sql Library is mysql-async, if you store true or false in sql that record 1 or 0 then if you query true or false data that return you string's of 1 or 0 . I think that fixed in oxmysql .
> 
> If this issue fixed please close issue .

i use oxmysql

**Comment by AstroNext** [comment] 2022-11-29 10:47
> i use oxmysql, issue persists for me with latest source code, so up to someone that can close it if it's considered fixed.

if you have problem with this bug, first check `v.stored` type then check it by correct type value's .

**Comment by iSentrie** [comment] 2022-11-29 11:07
The main reason opening this was duplication method, while vehicles still spawning (loading) you can reopen menu and it will still return that it's stored. I don't see how that PR fixed anything, plus it actually breaks for me everything and plus it returns different types for different people. So there are unanswered questions if we have the best code for most of users now? In the end now I have two problems instead of one with that last PR.

**Comment by Gellipapa** [comment] 2022-11-29 19:23
@iSentrie We won't close it until your problem is solved, but we need information to find the problem. 

What version are you using? It's supposed to be the latest, right?

What MYSQL are you using and which version of that?

What is the current status? As I see the store value is not good and that's why you can duplicate cars right? 

Answer these questions and we will solve your problem I thought it was a version problem but there is a specific problem here we need to investigate further. 

Thanks for the answers in advance.

**Comment by Gellipapa** [comment] 2022-11-29 19:26
> > I fix this problem in my server only with this function ( tonumber(v.stored) ) i think this fix this issue
> 
> this would only return nil then
> 
> @Gellipapa
> 
> > @iSentrie Remove cache folder and try retest, I think cached or you can't overwrite but interesting problem.
> 
> `v.stored` returns `true` or `false` ![image](https://user-images.githubusercontent.com/29688478/204505756-77c8b2b7-e9c5-4495-b048-4da563015b96.png)
> 
> changing code to
> 
> ```lua
> if v.stored == true then
>     label = label .. ('<span style="color:green;">%s</span>'):format(TranslateCap('garage_stored'))
> elseif v.stored == false then
>     label = label .. ('<span style="color:darkred;">%s</span>'):format(TranslateCap('garage_notstored'))
> end
> ```
> 
> or
> 
> ```lua
> if v.stored then
>     label = label .. ('<span style="color:green;">%s</span>'):format(TranslateCap('garage_stored'))
> else
>     label = label .. ('<span style="color:darkred;">%s</span>'):format(TranslateCap('garage_notstored'))
> end
> ```
> 
> fixes this issue, which leads to conclusion that any of this PR (#684) was unnecessary and only breaking the code. we don't need to write additionally `if v.stored == true then` or `if v.stored == 1 then` because simply `if v.stored then` was more than enough which i believe checks for both `true` and `1`. taking in mind that @AstroNext also had issue with it, you suppose to do more testing or ask around about opinions, how it actually supposed to be, since for us it works differently, which is non sense.

This can indeed be improved with a type check, but let's look more closely at the problem.

**Comment by iSentrie** [comment] 2022-12-01 12:00
> @iSentrie We won't close it until your problem is solved, but we need information to find the problem.
> 
> What version are you using? It's supposed to be the latest, right?
> 
> What MYSQL are you using and which version of that?
> 
> What is the current status? As I see the store value is not good and that's why you can duplicate cars right?
> 
> Answer these questions and we will solve your problem I thought it was a version problem but there is a specific problem here we need to investigate further.
> 
> Thanks for the answers in advance.

• esx_policejob - source version
• oxmysql v2.5.4

Current status is that I can't even spawn a single version with the source version (script returns true/false instead of 0/1). Duplication can be made by reopening car spawner immediately after choosing an vehicle (if vehicle isn't loaded yet, you will be able to duplicate it, but u gotta be fast and game has to be still loading the vehicle), this should be checked again after vehicles spawning is fixed (type check fix?)

**Comment by iSentrie** [comment] 2022-12-04 13:07
so conclusion?
• add check for both values, numeric and string

```if v.stored == 1 or v.stored ==  true then```

**Comment by Taavi-AU** [comment] 2022-12-04 13:08
> 

This is what the fix did, but sure.

**Comment by Taavi-AU** [comment] 2022-12-04 13:08
> so conclusion? • add check for both values, numeric and string
> 
> `if v.stored == 1 or v.stored == true then`
> 
> no need for elseif, it wont be stored in any case, so simply `else` is enough

If this works then sure

**Comment by Taavi-AU** [comment] 2023-01-10 04:17
This has already been fixed, works for everyone else but him, im not entirely sure why, the fix is already pushed and was a while ago now.

**Comment by Gellipapa** [comment] 2023-01-10 08:40
Hi! @iSentrie Does it work for you now?

**Comment by iSentrie** [comment] 2023-01-10 14:03
Were there any changes? Or you want me to test it again?

There was 2 issues:
1. Vehicle duplicates (there was changes after and I haven't tested after that)
2. Police vehicles cannot be spawned through police garage system (which was working fine before changes, which leads to two groups of users for whom it works and not, explained it above)

**Comment by Gellipapa** [comment] 2023-01-10 17:04
@iSentrie Hi! Thank you for send me status. There's no such thing as someone can do it and someone can't, then it's BUG. We'll fix it. I think as you write the boolean check variable might be the problem. Type should be forced :)

**Comment by iSentrie** [comment] 2023-01-10 21:49
@Gellipapa see my comment here https://github.com/esx-framework/esx-legacy/issues/515#issuecomment-1330414810 i have played with it in the past, thats what i found

**Comment by TheFantomas** [comment] 2023-04-05 21:41
@Thekuca Test

**Comment by TheFantomas** [comment] 2023-04-22 22:38
It seems that the problem was caused by a newer version of oxmysql. This issue should be resolved by this commit: https://github.com/esx-framework/esx_policejob/commit/aa20a4736ec8343fe68cb88aef0222ee83aa84c6.

**Closed by TheFantomas** 2023-04-22 22:38 UTC
Labels: bug, awaiting feedback, major problem
