### ISSUE TITLE
[BUG] ES_Extended | RemoveHudComponents

### ISSUE THREAD

**Issue by Luca8120** [esx-framework/esx_core#1470] opened 2024-11-16 16:25 UTC
**Describe the bug**
Some of the RemoveHudComponents dont work, such as AREA NAME, STREET NAME and CASH, MP_CASH

you can see it on the top right when i tap into the game and bottom right when i drive

**Debug Info (please complete the following information):**
 - OS: Windows Server 2022
 -  FiveM Artifact 11012
 - ESX Version: 1.11.2

sry for bad english iam german. 

here is a video of it: https://www.youtube.com/watch?v=en_jcxsS1Pw

![Image](https://github.com/user-attachments/assets/90bd88f7-ae56-4971-bebe-d2c128692f27)

**Comment by Luca8120** [comment] 2024-11-16 16:40
https://www.youtube.com/watch?v=X5brSsM7XhA

**Comment by Kenshiin13** [comment] 2024-11-19 11:49
@Luca8120 Is this a fresh ESX install from the receipe? Do you have any other scripts installed?

**Comment by Luca8120** [comment] 2024-11-19 17:55
@Kenshiin13 no it was a fresh install.

**Comment by Luca8120** [comment] 2024-11-19 17:55
now i just use the fivem natives to hide these things

**Comment by Luca8120** [comment] 2024-11-19 17:59
@Kenshiin13 but i dont know if it works on 1.11.3, only testet on 1.11.2. didnt even try after updating the hotfix. because i just set the natives at the end of the lua code again

**Comment by Kenshiin13** [comment] 2024-11-20 07:46
Unable to reproduce this on 1.11.3. I am going to close the issue for now. Thanks for the report @Luca8120!

**Closed by Kenshiin13** 2024-11-20 07:46 UTC
Labels: bug
